services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: gunicorn app:app