"""Add PaymentTransaction model

Revision ID: 183cc00a56d5
Revises: 
Create Date: 2025-05-10 04:10:08.003625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183cc00a56d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('received_on', sa.Date(), nullable=True))
        batch_op.alter_column('payment_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('fee_received_on')
        batch_op.drop_column('amount_received')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_received', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('fee_received_on', sa.DATE(), nullable=False))
        batch_op.alter_column('payment_mode',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('received_on')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
